### ISSUE TITLE
404 Error Nextcloud AIO

### ISSUE THREAD

**Issue by Joern85** [nextcloud/stt_whisper2#11]
### Steps to reproduce
1. choose file in nextcloud assistant at "Transcribe audio"-> "Upload from Nextcloud" (location of file does not matter, i tried my personal folder as well as /Talk/
2. click transcribe audio button

### Expected behaviour
audio file should be transcribed to text

### Actual behaviour
i get an error in Nextcloud "Task with id xx has failed"

<details>
<summary>Nextclod Log entry:</summary>

```
[stt_whisper2] Error: [404] Not Found <request: GET /ocs/v2.php/taskprocessing/tasks_provider/34/file/26813>
	POST /ocs/v1.php/apps/app_api/api/v1/log?format=json
	from 127.0.0.1 by -- at 27.11.2024, 23:06:35
```
</details>

<details>
<summary>Log from nc_app_stt_whisper2 Docker Container:</summary>

```
2024-11-27 22:06:32,947 - main - INFO - Next task: 34
2024-11-27 22:06:33,016 - httpx - INFO - HTTP Request: POST https://mydomain.de/ocs/v1.php/apps/app_api/api/v1/log?format=json "HTTP/1.1 200 OK"
2024-11-27 22:06:33,016 - main - INFO - model: faster-whisper-large-v3
2024-11-27 22:06:33,063 - httpx - INFO - HTTP Request: POST https://mydomain.de/ocs/v1.php/apps/app_api/api/v1/log?format=json "HTTP/1.1 200 OK"
[2024-11-27 22:06:35.052] [ctranslate2] [thread 18] [warning] The compute type inferred from the saved model is float16, but the target device or backend do not support efficient float16 computation. The model weights have been automatically converted to use the float32 compute type instead.
2024-11-27 22:06:35,202 - main - INFO - generating transcription
2024-11-27 22:06:35,289 - httpx - INFO - HTTP Request: POST https://mydomain.de/ocs/v1.php/apps/app_api/api/v1/log?format=json "HTTP/1.1 200 OK"
2024-11-27 22:06:35,467 - httpx - INFO - HTTP Request: GET https://mydomain.de/ocs/v2.php/taskprocessing/tasks_provider/34/file/26813?format=json "HTTP/1.1 404 Not Found"
2024-11-27 22:06:35,467 - main - ERROR - [404] Not Found <request: GET /ocs/v2.php/taskprocessing/tasks_provider/34/file/26813>
```
</details>
### Server configuration

Nextcloud AIO v10.0.0 on Ubuntu 24.04 with nginx reverse proxy

<details>
<summary>List of activated apps</summary>

```
- activity: 3.0.0
  - admin_audit: 1.20.0
  - app_api: 4.0.0
  - assistant: 2.1.1
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.5
  - call_summary_bot: 2.0.0
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.1
  - contactsinteraction: 1.11.0
  - context_chat: 3.1.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.2
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_antivirus: 5.6.1
  - files_downloadlimit: 3.0.0
  - files_fulltextsearch: 30.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - fulltextsearch: 30.0.0
  - fulltextsearch_elasticsearch: 30.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.3
  - nextcloud-aio: 0.6.0
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - notify_push: 0.7.0
  - oauth2: 1.18.1
  - onlyoffice: 9.5.0
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.2
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - text2image_stablediffusion: 2.0.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - user_migration: 7.0.1
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - whiteboard: 1.0.4
  - workflowengine: 2.12.0

```
</details>

<details>
<summary>Nextcloud configuration</summary>

```
{
    "system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "mydomain.de",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "mydomain.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "30.0.2.2",
        "overwrite.cli.url": "https:\/\/mydomain.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updatedirectory": "\/nc-updater",
        "loglevel": 3,
        "app_install_overwrite": [
            "nextcloud-aio"
        ],
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": 10485760,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "jpeg_quality": 60,
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "7": "OC\\Preview\\Krita",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": 30,
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "maintenance_window_start": 100,
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 14400,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "auth.bruteforce.protection.enabled": true,
        "ratelimit.protection.enabled": true,
        "files_external_allow_create_new_local": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_key": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "documentation_url.server_logs": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/5425",
        "onlyoffice": {
            "jwt_secret": "***REMOVED SENSITIVE VALUE***",
            "jwt_header": "AuthorizationJwt"
        },
        "DOMAIN": "mydomain.de"
    }
}

```
</details>

### Browser

**Browser name:** Chrome

**Browser version:** 131.0.6778.86

**Operating system:** Windows

<details>
<summary>Browser log</summary>

```
preview:1 
        
        
       GET https://mydomain.de/core/preview?fileId=26349&x=32&y=32&mimeFallback=true&a=0&c=67463e6f7d5f3 404 (Not Found)
preview:1 
        
        
       GET https://mydomain.de/core/preview?fileId=268&x=32&y=32&mimeFallback=true&a=0&c=673911e2a5ad5 404 (Not Found)
index-D-hFlxhk.chunk.mjs:3 F: FilePicker: No nodes selected
    at https://mydomain.de/custom_apps/assistant/js/index-9v6di3ld.chunk.mjs:3:2127
    at close (https://mydomain.de/custom_apps/assistant/js/index-9v6di3ld.chunk.mjs:3:508)
    at Qe (https://mydomain.de/custom_apps/assistant/js/index-D-hFlxhk.chunk.mjs:3:25970)
    at r.a (https://mydomain.de/custom_apps/assistant/js/index-D-hFlxhk.chunk.mjs:3:16160)
    at Qe (https://mydomain.de/custom_apps/assistant/js/index-D-hFlxhk.chunk.mjs:3:25970)
    at e.$emit (https://mydomain.de/custom_apps/assistant/js/index-D-hFlxhk.chunk.mjs:3:31565)
    at o (https://mydomain.de/custom_apps/assistant/js/FilePicker-kaHdQqaz-CG2LpugX.chunk.mjs:4819:39795)
    at Object.callback (https://mydomain.de/custom_apps/assistant/js/FilePicker-kaHdQqaz-CG2LpugX.chunk.mjs:4819:39738)
    at handleClick (https://mydomain.de/custom_apps/assistant/js/NcNoteCard-CImn6F9p-CIwqiD1W.chunk.mjs:934:1983)
    at Qe (https://mydomain.de/custom_apps/assistant/js/index-D-hFlxhk.chunk.mjs:3:25970)
Oi @ index-D-hFlxhk.chunk.mjs:3
ji @ index-D-hFlxhk.chunk.mjs:3
Rt @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
Promise.catch
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
click @ index-D-hFlxhk.chunk.mjs:13
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Md.n._wrapper @ index-D-hFlxhk.chunk.mjs:3
preview:1 
        
        
       GET https://mydomain.de/core/preview?fileId=26349&x=32&y=32&mimeFallback=true&a=0&c=67463e6f7d5f3 404 (Not Found)
preview:1 
        
        
       GET https://mydomain.de/core/preview?fileId=268&x=32&y=32&mimeFallback=true&a=0&c=673911e2a5ad5 404 (Not Found)
index-D-hFlxhk.chunk.mjs:13 You need to fill either the text or the ariaLabel props in the button component. {text: undefined, ariaLabel: null} r {_uid: 870, _isVue: true, __v_skip: true, _scope: e, $options: {…}, …}
render @ index-D-hFlxhk.chunk.mjs:13
Rv.e._render @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e @ index-D-hFlxhk.chunk.mjs:3
oc @ index-D-hFlxhk.chunk.mjs:3
K.$mount @ index-D-hFlxhk.chunk.mjs:3
init @ index-D-hFlxhk.chunk.mjs:3
d @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
Y @ index-D-hFlxhk.chunk.mjs:3
O @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
e._update @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e.run @ index-D-hFlxhk.chunk.mjs:3
sc @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
ou @ index-D-hFlxhk.chunk.mjs:3
Promise.then
wa @ index-D-hFlxhk.chunk.mjs:3
Va @ index-D-hFlxhk.chunk.mjs:3
Yo @ index-D-hFlxhk.chunk.mjs:3
e.update @ index-D-hFlxhk.chunk.mjs:3
e.notify @ index-D-hFlxhk.chunk.mjs:3
set @ index-D-hFlxhk.chunk.mjs:3
handleClick @ NcNoteCard-CImn6F9p-CIwqiD1W.chunk.mjs:934
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
click @ index-D-hFlxhk.chunk.mjs:13
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Md.n._wrapper @ index-D-hFlxhk.chunk.mjs:3
index-D-hFlxhk.chunk.mjs:13 You need to fill either the text or the ariaLabel props in the button component. {text: undefined, ariaLabel: null} r {_uid: 874, _isVue: true, __v_skip: true, _scope: e, $options: {…}, …}
render @ index-D-hFlxhk.chunk.mjs:13
Rv.e._render @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e @ index-D-hFlxhk.chunk.mjs:3
oc @ index-D-hFlxhk.chunk.mjs:3
K.$mount @ index-D-hFlxhk.chunk.mjs:3
init @ index-D-hFlxhk.chunk.mjs:3
d @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
Y @ index-D-hFlxhk.chunk.mjs:3
O @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
e._update @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e.run @ index-D-hFlxhk.chunk.mjs:3
sc @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
ou @ index-D-hFlxhk.chunk.mjs:3
Promise.then
wa @ index-D-hFlxhk.chunk.mjs:3
Va @ index-D-hFlxhk.chunk.mjs:3
Yo @ index-D-hFlxhk.chunk.mjs:3
e.update @ index-D-hFlxhk.chunk.mjs:3
e.notify @ index-D-hFlxhk.chunk.mjs:3
set @ index-D-hFlxhk.chunk.mjs:3
Mn.st.set @ index-D-hFlxhk.chunk.mjs:3
update:inputs @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:40
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
update:values @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
onValueChange @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
update:value @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
update:value @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
onFileUploaded @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Promise.then
onUploadFileSelected @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Md.n._wrapper @ index-D-hFlxhk.chunk.mjs:3
index-D-hFlxhk.chunk.mjs:13 You need to fill either the text or the ariaLabel props in the button component. {text: undefined, ariaLabel: null} r {_uid: 874, _isVue: true, __v_skip: true, _scope: e, $options: {…}, …}
render @ index-D-hFlxhk.chunk.mjs:13
Rv.e._render @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e.run @ index-D-hFlxhk.chunk.mjs:3
sc @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
ou @ index-D-hFlxhk.chunk.mjs:3
Promise.then
wa @ index-D-hFlxhk.chunk.mjs:3
Va @ index-D-hFlxhk.chunk.mjs:3
Yo @ index-D-hFlxhk.chunk.mjs:3
e.update @ index-D-hFlxhk.chunk.mjs:3
e.notify @ index-D-hFlxhk.chunk.mjs:3
set @ index-D-hFlxhk.chunk.mjs:3
Mn.st.set @ index-D-hFlxhk.chunk.mjs:3
update:is-uploading @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Promise.then
onUploadFileSelected @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:35
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Md.n._wrapper @ index-D-hFlxhk.chunk.mjs:3
assistant-CDnyT5Bj.chunk.mjs:3 [assistant] Task failed {id: 37, type: 'core:audio2text', lastUpdated: 1732747461, status: 'STATUS_FAILED', userId: 'admin', …}appId: "assistant"completionExpectedAt: 1732747573customId: ""endedAt: 1732747461id: 37input: {input: 27057}lastUpdated: 1732747461output: nullprogress: 0scheduledAt: 1732747453startedAt: nullstatus: "STATUS_FAILED"type: "core:audio2text"userId: "admin"[[Prototype]]: Object
(anonymous) @ assistant-CDnyT5Bj.chunk.mjs:3
Promise.then
(anonymous) @ assistant-CDnyT5Bj.chunk.mjs:3
Promise.then
L @ assistant-CDnyT5Bj.chunk.mjs:3
(anonymous) @ assistant-CDnyT5Bj.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
onSyncSubmit @ AssistantTextProcessingModal-DnEodIwO.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
onSyncSubmit @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:40
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
click @ index-D-hFlxhk.chunk.mjs:13
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Md.n._wrapper @ index-D-hFlxhk.chunk.mjs:3
index-D-hFlxhk.chunk.mjs:13 You need to fill either the text or the ariaLabel props in the button component. {text: undefined, ariaLabel: null} r {_uid: 916, _isVue: true, __v_skip: true, _scope: e, $options: {…}, …}
render @ index-D-hFlxhk.chunk.mjs:13
Rv.e._render @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e @ index-D-hFlxhk.chunk.mjs:3
oc @ index-D-hFlxhk.chunk.mjs:3
K.$mount @ index-D-hFlxhk.chunk.mjs:3
init @ index-D-hFlxhk.chunk.mjs:3
d @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
e._update @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e @ index-D-hFlxhk.chunk.mjs:3
oc @ index-D-hFlxhk.chunk.mjs:3
K.$mount @ index-D-hFlxhk.chunk.mjs:3
init @ index-D-hFlxhk.chunk.mjs:3
d @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
e._update @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e @ index-D-hFlxhk.chunk.mjs:3
oc @ index-D-hFlxhk.chunk.mjs:3
K.$mount @ index-D-hFlxhk.chunk.mjs:3
init @ index-D-hFlxhk.chunk.mjs:3
d @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
e._update @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e @ index-D-hFlxhk.chunk.mjs:3
oc @ index-D-hFlxhk.chunk.mjs:3
K.$mount @ index-D-hFlxhk.chunk.mjs:3
init @ index-D-hFlxhk.chunk.mjs:3
d @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
e._update @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e @ index-D-hFlxhk.chunk.mjs:3
oc @ index-D-hFlxhk.chunk.mjs:3
K.$mount @ index-D-hFlxhk.chunk.mjs:3
init @ index-D-hFlxhk.chunk.mjs:3
d @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
k @ index-D-hFlxhk.chunk.mjs:3
l @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
e._update @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e.run @ index-D-hFlxhk.chunk.mjs:3
sc @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
ou @ index-D-hFlxhk.chunk.mjs:3
Promise.then
wa @ index-D-hFlxhk.chunk.mjs:3
Va @ index-D-hFlxhk.chunk.mjs:3
Yo @ index-D-hFlxhk.chunk.mjs:3
e.update @ index-D-hFlxhk.chunk.mjs:3
e.notify @ index-D-hFlxhk.chunk.mjs:3
set @ index-D-hFlxhk.chunk.mjs:3
Mn.st.set @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:40
Promise.then
getTaskTypes @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:40
mounted @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:40
Qe @ index-D-hFlxhk.chunk.mjs:3
je @ index-D-hFlxhk.chunk.mjs:3
insert @ index-D-hFlxhk.chunk.mjs:3
U @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
e._update @ index-D-hFlxhk.chunk.mjs:3
u @ index-D-hFlxhk.chunk.mjs:3
e.get @ index-D-hFlxhk.chunk.mjs:3
e.run @ index-D-hFlxhk.chunk.mjs:3
sc @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ index-D-hFlxhk.chunk.mjs:3
ou @ index-D-hFlxhk.chunk.mjs:3
Promise.then
wa @ index-D-hFlxhk.chunk.mjs:3
Va @ index-D-hFlxhk.chunk.mjs:3
Yo @ index-D-hFlxhk.chunk.mjs:3
e.update @ index-D-hFlxhk.chunk.mjs:3
e.notify @ index-D-hFlxhk.chunk.mjs:3
set @ index-D-hFlxhk.chunk.mjs:3
Mn.st.set @ index-D-hFlxhk.chunk.mjs:3
(anonymous) @ assistant-CDnyT5Bj.chunk.mjs:3
Promise.then
(anonymous) @ assistant-CDnyT5Bj.chunk.mjs:3
Promise.then
L @ assistant-CDnyT5Bj.chunk.mjs:3
(anonymous) @ assistant-CDnyT5Bj.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
onSyncSubmit @ AssistantTextProcessingModal-DnEodIwO.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
onSyncSubmit @ ScheduledEmptyContent-Ds5wiK4j.chunk.mjs:40
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Qe @ index-D-hFlxhk.chunk.mjs:3
e.$emit @ index-D-hFlxhk.chunk.mjs:3
click @ index-D-hFlxhk.chunk.mjs:13
Qe @ index-D-hFlxhk.chunk.mjs:3
a @ index-D-hFlxhk.chunk.mjs:3
Md.n._wrapper @ index-D-hFlxhk.chunk.mjs:3

```

</details>

**Comment by marcelklehr** [comment]
Hello  @Joern85 
Thank you for reporting this issue!
Is this still happening for you? I believe we fixed a similar issue recently in Nextcloud Server.
